export const dummyTeams = [
  // Osaka Boys
  {
    id: "1",
    name: "大阪北ボーイズ",
    prefecture: "osaka",
    area: "北摂",
    league: "boys",
    branch: "大阪北支部",
    description: "全国大会常連の強豪。プロ野球選手も多数輩出。",
    url: "https://example.com",
    tags: ["プロ輩出", "全国優勝", "伝統"],
  },
  {
    id: "2",
    name: "大阪南ボーイズ",
    prefecture: "osaka",
    area: "堺・泉州",
    league: "boys",
    branch: "大阪南支部",
    description: "「全力疾走」をスローガンに、人間形成を重視。",
    url: "https://example.com",
    tags: ["人間形成", "高校進路"],
  },
  {
    id: "3",
    name: "枚方ボーイズ",
    prefecture: "osaka",
    area: "北河内",
    league: "boys",
    branch: "大阪北支部",
    description: "日本一の経験を持つ名門チーム。専用グラウンド完備。",
    url: "https://example.com",
    tags: ["全国優勝", "専用球場", "伝統"],
  },
  {
    id: "4",
    name: "東大阪北ボーイズ",
    prefecture: "osaka",
    area: "中河内",
    league: "boys",
    branch: "大阪東支部",
    description: "基本技術の徹底と、高校で通用する体づくり。",
    url: "https://example.com",
    tags: ["高校進路", "基礎重視"],
  },
  {
    id: "5",
    name: "大阪中央ボーイズ",
    prefecture: "osaka",
    area: "大阪市内",
    league: "boys",
    branch: "大阪中央支部",
    description: "文武両道を掲げ、学習サポートも充実。",
    url: "https://example.com",
    tags: ["文武両道", "学習サポート"],
  },

  // Hyogo Boys
  {
    id: "11",
    name: "神戸中央ボーイズ",
    prefecture: "hyogo",
    area: "神戸市",
    league: "boys",
    branch: "兵庫県支部",
    description: "兵庫県屈指の強豪。甲子園球児を多数送り出す。",
    url: "https://example.com",
    tags: ["プロ輩出", "高校進路", "伝統"],
  },
  {
    id: "12",
    name: "明石ボーイズ",
    prefecture: "hyogo",
    area: "明石市",
    league: "boys",
    branch: "兵庫県支部",
    description: "明るく元気な野球。チームワークの良さが特徴。",
    url: "https://example.com",
    tags: ["チームワーク", "初心者歓迎"],
  },
  {
    id: "13",
    name: "兵庫伊丹ボーイズ",
    prefecture: "hyogo",
    area: "伊丹市",
    league: "boys",
    branch: "兵庫県支部",
    description: "厳しい練習の中で培われる精神力。",
    url: "https://example.com",
    tags: ["メンタル強化", "高校進路"],
  },
  {
    id: "14",
    name: "西宮ボーイズ",
    prefecture: "hyogo",
    area: "西宮市",
    league: "boys",
    branch: "兵庫県支部",
    description: "礼儀正しさと感謝の心を大切にする。",
    url: "https://example.com",
    tags: ["人間形成", "礼儀重視"],
  },
  {
    id: "15",
    name: "宝塚ボーイズ",
    prefecture: "hyogo",
    area: "宝塚市",
    league: "boys",
    branch: "兵庫県支部",
    description: "自然豊かな環境で伸び伸びとプレー。",
    url: "https://example.com",
    tags: ["専用球場", "のびのび"],
  },
];

